project:
  type: website
  output-dir: docs
  resources:
    - files
    - .quarto/_extensions/jmgirard/embedpdf

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd 
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



